schema_version = "1.0.0"

id = "modifier_stack_manager"
version = "1.2.0"
name = "Modifier Stack Manager"
tagline = "A UI List implementation for Blender's modifier stack"
maintainer = "Salai Vedha Viradhan"
type = "add-on"

tags = ["Object", "User Interface"]

website = "https://github.com/salaivv/modifier-stack-manager"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]